<?php
/**
 * PRISMA Installer
 */
session_start();

$lock_file = __DIR__ . '/install.lock';
$config_file = __DIR__ . '/includes/config.php';

if (file_exists($lock_file) || file_exists($config_file)) {
    die("<div style='font-family: sans-serif; text-align: center; padding: 50px;'>
            <h2 style='color: #ff3e1d;'>Akses Ditolak</h2>
            <p>Aplikasi PRISMA sudah terpasang. Untuk keamanan, installer telah dinonaktifkan.</p>
            <p style='color: #8592a3; font-size: 0.9rem;'>Jika ingin instalasi ulang, hapus file <code>install.lock</code> dan <code>includes/config.php</code> secara manual di server.</p>
            <a href='index.php' style='color: #696cff; text-decoration: none;'>Kembali ke Beranda</a>
         </div>");
}

$error = '';
$success = '';
$step = isset($_GET['step']) ? (int)$_GET['step'] : 1;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if ($step === 1) {
        // Database Setup
        $db_host = $_POST['db_host'] ?? 'localhost';
        $db_name = $_POST['db_name'] ?? 'prisma_db';
        $db_user = $_POST['db_user'] ?? 'root';
        $db_pass = $_POST['db_pass'] ?? '';

        try {
            // Test Connection
            $pdo = new PDO("mysql:host=$db_host", $db_user, $db_pass);
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            
            // Create Database
            $pdo->exec("CREATE DATABASE IF NOT EXISTS `$db_name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
            $pdo->exec("USE `$db_name`");

            // Import SQL Schema
            $sql_file = __DIR__ . '/prisma_db.sql';
            if (file_exists($sql_file)) {
                $sql = file_get_contents($sql_file);
                // Remove USE statement if it exists in SQL to avoid conflict
                $sql = preg_replace('/USE `?prisma_db`?;/', '', $sql);
                $pdo->exec($sql);
            } else {
                throw new Exception("File schema 'prisma_db.sql' tidak ditemukan!");
            }

            // Save DB credentials in session for next step
            $_SESSION['db_config'] = [
                'host' => $db_host,
                'name' => $db_name,
                'user' => $db_user,
                'pass' => $db_pass
            ];

            header("Location: install.php?step=2");
            exit;
        } catch (Exception $e) {
            $error = "Terjadi kesalahan: " . $e->getMessage();
        }
    } elseif ($step === 2) {
        // Admin Setup
        $admin_user = $_POST['admin_user'] ?? 'admin';
        $admin_pass = $_POST['admin_pass'] ?? '';
        $admin_nama = $_POST['admin_nama'] ?? 'Administrator';

        if (strlen($admin_pass) < 6) {
            $error = "Password minimal 6 karakter!";
        } else {
            try {
                $conf = $_SESSION['db_config'];
                $pdo = new PDO("mysql:host={$conf['host']};dbname={$conf['name']}", $conf['user'], $conf['pass']);
                $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

                // Clear existing admins/users if any (fresh start)
                $pdo->exec("DELETE FROM users WHERE role = 'admin'");
                
                // Hash Password
                $hashed_pass = password_hash($admin_pass, PASSWORD_DEFAULT);

                // Insert User
                $stmt = $pdo->prepare("INSERT INTO users (username, password, role) VALUES (?, ?, 'admin')");
                $stmt->execute([$admin_user, $hashed_pass]);
                $user_id = $pdo->lastInsertId();

                // Insert Admin Profile
                $stmt = $pdo->prepare("INSERT INTO admins (user_id, nama_lengkap) VALUES (?, ?)");
                $stmt->execute([$user_id, $admin_nama]);

                // Generate config.php
                $config_content = "<?php\n"
                    . "/**\n"
                    . " * PRISMA Configuration File (Generated by Installer)\n"
                    . " */\n\n"
                    . "error_reporting(E_ALL);\n"
                    . "ini_set('display_errors', 1);\n"
                    . "date_default_timezone_set('Asia/Jakarta');\n\n"
                    . "define('DB_HOST', '{$conf['host']}');\n"
                    . "define('DB_NAME', '{$conf['name']}');\n"
                    . "define('DB_USER', '{$conf['user']}');\n"
                    . "define('DB_PASS', '{$conf['pass']}');\n\n"
                    . "define('BASE_URL', 'http://' . \$_SERVER['HTTP_HOST'] . rtrim(dirname(\$_SERVER['PHP_SELF']), '/admin/guru/siswa/ajax') . '/');\n\n"
                    . "define('APP_NAME', 'PRISMA');\n"
                    . "define('SCHOOL_NAME', 'MTsN 11 Majalengka');\n"
                    . "define('DEFAULT_YEAR', '2025/2026');\n\n"
                    . "if (session_status() === PHP_SESSION_NONE) {\n"
                    . "    session_start();\n"
                    . "}\n\n"
                    . "require_once __DIR__ . '/../vendor/autoload.php';\n\n"
                    . "function base_url(\$path = '') {\n"
                    . "    return BASE_URL . ltrim(\$path, '/');\n"
                    . "}\n";

                file_put_contents(__DIR__ . '/includes/config.php', $config_content);
                
                // Create Lock File
                file_put_contents($lock_file, date('Y-m-d H:i:s'));

                unset($_SESSION['db_config']);
                $step = 3;
            } catch (Exception $e) {
                $error = "Gagal membuat akun admin: " . $e->getMessage();
            }
        }
    }
}
?>
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Installer PRISMA - MTsN 11 Majalengka</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:wght@400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@2.1.4/css/boxicons.min.css" />
    <style>
        body { background-color: #f5f5f9; font-family: 'Public Sans', sans-serif; }
        .installer-wrapper { min-height: 100vh; display: flex; align-items: center; justify-content: center; padding: 20px; }
        .card { width: 100%; max-width: 500px; border: none; box-shadow: 0 2px 10px rgba(0,0,0,0.1); border-radius: 12px; }
        .btn-primary { background-color: #696cff; border: none; }
        .btn-primary:hover { background-color: #5f61e6; }
        .step-indicator { display: flex; justify-content: space-between; margin-bottom: 30px; position: relative; }
        .step-indicator::before { content: ""; position: absolute; top: 15px; left: 0; right: 0; height: 2px; background: #d9dee3; z-index: 1; }
        .step-number { width: 32px; height: 32px; border-radius: 50%; background: #fff; border: 2px solid #d9dee3; display: flex; align-items: center; justify-content: center; z-index: 2; font-weight: 600; color: #8592a3; }
        .step-number.active { background: #696cff; border-color: #696cff; color: #fff; }
        .step-number.completed { background: #71dd37; border-color: #71dd37; color: #fff; }
    </style>
</head>
<body>

<div class="installer-wrapper text-center">
    <div class="card p-4">
        <div class="mb-4">
            <img src="assets/img/logo.png" alt="Logo" height="100" class="mb-3">
            <p class="text-muted">Setup Aplikasi Penilaian Ujian Praktik</p>
        </div>

        <div class="step-indicator">
            <div class="step-number <?= $step >= 1 ? ($step > 1 ? 'completed' : 'active') : '' ?>">1</div>
            <div class="step-number <?= $step >= 2 ? ($step > 2 ? 'completed' : 'active') : '' ?>">2</div>
            <div class="step-number <?= $step >= 3 ? 'completed' : '' ?>">3</div>
        </div>

        <?php if ($error): ?>
            <div class="alert alert-danger text-start py-2" style="font-size: 0.9rem;">
                <i class="bx bx-error me-1"></i> <?= $error ?>
            </div>
        <?php endif; ?>

        <?php if ($step === 1): ?>
            <form method="POST" class="text-start">
                <div class="mb-3">
                    <label class="form-label">DB Host</label>
                    <input type="text" name="db_host" class="form-control" value="localhost" required>
                </div>
                <div class="mb-3">
                    <label class="form-label">Nama Database</label>
                    <input type="text" name="db_name" class="form-control" value="prisma_db" required>
                </div>
                <div class="mb-3">
                    <label class="form-label">DB Username</label>
                    <input type="text" name="db_user" class="form-control" value="root" required>
                </div>
                <div class="mb-3">
                    <label class="form-label">DB Password</label>
                    <input type="password" name="db_pass" class="form-control">
                </div>
                <button type="submit" class="btn btn-primary w-100">Koneksi & Buat Database</button>
            </form>

        <?php elseif ($step === 2): ?>
            <form method="POST" class="text-start">
                <div class="alert alert-success py-2 mb-3" style="font-size: 0.85rem;">
                    <i class="bx bx-check-circle"></i> Database berhasil diatur!
                </div>
                <div class="mb-3">
                    <label class="form-label">Username Admin</label>
                    <input type="text" name="admin_user" class="form-control" value="admin" required>
                </div>
                <div class="mb-3">
                    <label class="form-label">Nama Lengkap</label>
                    <input type="text" name="admin_nama" class="form-control" placeholder="Administrator PRISMA" required>
                </div>
                <div class="mb-3">
                    <label class="form-label">Password Admin</label>
                    <input type="password" name="admin_pass" class="form-control" placeholder="Minimal 6 karakter" required>
                </div>
                <button type="submit" class="btn btn-primary w-100">Simpan & Selesaikan Instalasi</button>
            </form>

        <?php elseif ($step === 3): ?>
            <div class="text-center py-4">
                <div class="mb-3">
                    <i class="bx bx-check-circle text-success" style="font-size: 5rem;"></i>
                </div>
                <h4>Instalasi Berhasil!</h4>
                <p class="text-muted">Aplikasi PRISMA siap digunakan. File <code>install.lock</code> telah dibuat untuk keamanan.</p>
                <div class="mt-4">
                    <a href="login.php" class="btn btn-primary w-100">Ke Halaman Login</a>
                </div>
            </div>
        <?php endif; ?>

        <div class="mt-4 text-muted" style="font-size: 0.75rem;">
            &copy; 2026 MTsN 11 Majalengka
        </div>
    </div>
</div>

</body>
</html>
